title: Siddhant Sindhkar
logo: assets/ProfilePic.jpg
description:
  <p align="center">
  Mumbai, India
  <br> (+91) 8928350845
  <br> siddhantsindhkar.49@gmail.com
  <br> <a href="assets/.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/siddhant-sindhkar-a38bbb1b3/">LinkedIn</a> |
  <a href="https://github.com/siddhant4902">GitHub</a>
  <a href="https://medium.com/@sidsin0492">Medium</a>
  <br> <a href="https://www.kaggle.com/siddhantsindhkar">Kaggle</a> |
  </p>
  
  <p align="justify">
  I am an aspiring <b>data scientist</b> who enjoys connecting the dots by the use of technology. 
  <br>
  I am pursing <b>Master's Degree in Data Science at University of Milano-Bicocca</b>, where I’m receiving solid training in all the major fields of Data Science.
  <br>
  I have a hard science education, having achieved a <b>Bachelor's Degree in Chemical Sciences and Technologies</b>.
  <br>
  I consider myself a kind, empathetic, creative and determined person. I am pragmatic and organized, yet flexible.
  <br><br>
  </p>


# show_downloads: true
theme: jekyll-theme-minimal
