title: Siddhant Sindhkar
logo: assets/ProfilePic.jpg
description:
  <p align="center">
  Mumbai, India
  <br> (+91) 8928350845
  <br> siddhantsindhkar.49@gmail.com
  <br> <a href="assets/.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/siddhant-sindhkar-a38bbb1b3/">LinkedIn</a>
  <br> <a href="https://medium.com/@sidsin0492">Medium</a>|
  <a href="https://github.com/siddhant4902">GitHub</a>|
  <a href="https://www.kaggle.com/siddhantsindhkar">Kaggle</a> 
  </p>
  
  <p align="justify">
  I am a <b>data scientist</b>, who thrives on creating informed decision making for real world problems.
  <br>
  My Bachelor's degree in Data Science has equipped me with a strong foundation in Machine Learning, Deep Learning, NLP, Big Data, and Finance.
  
  I am also a student at the CFA Institute, studying to get my Level-1 certification, committing to apply data science principles in the financial industry.
  <br>
  I consider myself an passionate, analytical, empathetic, creative and determined person. I am also adaptable to changing situations, allowing me to thrive in dynamic environments.
  <br><br>
  </p>


# show_downloads: true
theme: jekyll-theme-minimal
